### ISSUE TITLE
Error on Synology

### ISSUE THREAD

**Issue by deadlyknapsack** [jlentink/transip-dyndns#1]
Dit is precies waar ik naar op zoek was! Ik heb een Synology NAS staan, waar ik dit op wil draaien. Ik heb de instructies op GitHub gevolgd, maar ik krijg de volgende melding:

The PHP SOAP extension doesn't seem to be installed. You need to install the PHP SOAP extension. (See: http://www.php.net/manual/en/book.soap.php)

Ik heb bij mijn webservices gekeken en daar staat SOAP aangevinkt en hierbij ook de bevestiging:

http://www.skypager.nl/test.php

Heb je een idee hoe ik dit op kan lossen?

**Comment by jlentink** [comment]
Dan staat de soap module niet aan in de php. ik heb een checker toegevoegd aan het script.
