### ISSUE TITLE
Can't get the script to work.

### ISSUE THREAD

**Issue by Deadbeef64** [jlentink/transip-dyndns#2]
Used:
TransIP API 5.5
Running IIS7 on win 10 in local lan and WAN ip adress that's changing every day.

Executed from webbrowser as a php file with parameters like this "?username=kennetht&private-key=trans-ip.key&domain=kennethtan.nl"

I'm not a developer, but please could you help me to get this script executed on my win10 pc

**Comment by jlentink** [comment]
What you can do is create a powershell script and run that with scheduled tasks.

```
# Set up references to executable and script
$PhpExe  = "C:\path\to\php\install\dir\php.exe"
$PhpFile = "C:\path\to\script.php"

# Create arguments from Script location
# usually php.exe is invoked from console like: 
# php.exe -f "C:\path\myscript.php"
$PhpArgs = ' --username kennetht --private-key trans-ip.key --domain kennethtan.nl' -f $PhpFile

# Invoke, using the call operator
$PhpOutput = & $PhpExe $PhpArgs
```
